on: push
name: DevToko
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: 	ftpupload.net
        username: epiz_27708217
        password: ${{ secrets.ftp_password }}
        port: 21
        dry-run: true
        server-dir: htdocs/
